api_platform:
    title: CoPath API
    description: API for CoPath application
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']